name: Main Deployment

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
      NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      NEXT_PUBLIC_RAZORPAY_KEY_ID: ${{ secrets.NEXT_PUBLIC_RAZORPAY_KEY_ID }}
      RAZORPAY_KEY_SECRET: ${{ secrets.RAZORPAY_KEY_SECRET }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    strategy:
      matrix:
        node-version: [18.17.0]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: npm ci --legacy-peer-deps
      - run: npm run build

      - name: Upload to VPS
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USER }}
          TARGET: ${{ secrets.LIVE_PATH }}
          SOURCE: "."
          EXCLUDE: "/.git/, .env"

      - name: Run Prisma Migrations
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_DEPLOY_KEY }}
          script: |
            cd ${{ secrets.LIVE_PATH }}
            export DATABASE_URL=${{ secrets.DATABASE_URL }}
            npx prisma migrate deploy

      - name: Verify Prisma Migrations
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_DEPLOY_KEY }}
          script: |
            cd ${{ secrets.LIVE_PATH }}
            export DATABASE_URL=${{ secrets.DATABASE_URL }}
            npx prisma migrate status

      - name: Restart App via PM2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_DEPLOY_KEY }}
          script: |
            cd ${{ secrets.LIVE_PATH }}
            npm install
            pm2 restart milele || pm2 start npm --name "milele" -- start
