name: QA Deployment

on:
  push:
    branches: ["qa-milele"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
      NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL_QA }}
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      NEXT_PUBLIC_RAZORPAY_KEY_ID: ${{ secrets.NEXT_PUBLIC_RAZORPAY_KEY_ID_QA }}
      RAZORPAY_KEY_SECRET: ${{ secrets.RAZORPAY_KEY_SECRET }}

    strategy:
      matrix:
        node-version: [18.17.0]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: npm ci --legacy-peer-deps
      - run: npm run build

      - name: Upload to VPS
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USER }}
          TARGET: ${{ secrets.LIVE_PATH_QA }}
          SOURCE: "."
          EXCLUDE: "/.git/, .env"

      - name: Restart App via PM2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_DEPLOY_KEY }}
          script: |
            cd ${{ secrets.LIVE_PATH_QA }}
            npm install
            pm2 restart mr-mard || pm2 start npm --name "mr-mard" -- start
